initial commit
IvanKlimkin/java-explore-with-me pull request #1
Opened 2022-11-29 14:51 UTC by IvanKlimkin

2022-11-30 15:02 UTC, IvanKlimkin commented
Ошибка в проверке по нулевому полю в объекте локация, по заданию not null.

2022-11-30 20:19 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев к коду, будут вопросы приходите. Еще не смог найти у Вас, где вы в основном сервисе запрашиваете статистику из второго, подсветите пожалуйста этот момент в комментарии.

2022-11-30 20:19 UTC, Frilock commented on README.md
>  # java-explore-with-me
Первое что бросается в глаза это название Pull Request, там кратко должна быть отражена суть сделанного.

2022-11-30 20:19 UTC, Frilock commented on README.md
>  Template repository for ExploreWithMe project.
Знаю, что по ТЗ у Вас сказано, чтобы в Readme файле была ссылка на проект. Предлагаю также в данном файле разместить информацию о самом проекте, за что каждый модуль отвечает, как проект собирается. Чтобы стороннему человеку который видит Ваш проект было проще. Кроме того, можно описать специфические конфиг файлы, если они есть. Это хорошая практика.

2022-11-30 20:19 UTC, Frilock commented on ewm-service/pom.xml
> +            <version>2021.0.5</version>
Общий комментарий по pom файлам. Смотрите, у Вас многомодульный проект, сейчас он состоит из 2х модулей, но возможно их будет больше. Так вот, хочется чтобы в приложении была одна точка добавления зависимостей. Такой обычно делают корневой pom файл. Там нужно сделать блок dependencyManager и добавлять те библиотеки которых нет в parent, а затем уже в других pom файлах подключать, но уже без указания версии. Кроме того, версии этих библиотек правильнее указывать в properties, поскольку pom файлы бывают довольно больших размеров и изменение версии может быть не такой простой задачей.

2022-11-30 20:19 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/category/mapper/CategoryMapper.java
> +    public Category toCategory(CategoryDto categoryDto) {
Я вообще подумал о том, что в мапперах бы по хорошему нужно проверять, что входящий объект, как в данном случае categoryDto not null. Или хотя бы тут поставить аннотацию nonNull, чтобы этот момент не смущал никого

2022-11-30 20:19 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/category/service/CategoryServiceImpl.java
> +        return categoryMapper.toDto(categoryRepository.findById(
Вообще правильно по идее переносить 
.orElseThrow(() -> new ServerException("Категория с таким ID отсутствует.")));
А catId на старой строке оставить. 

Кроме того, лично меня смущает сокращение catId, мне кажется лучше было бы назвать categoryId

2022-11-30 20:19 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/compilation/dto/CompilationDto.java
> +    List<EventShortDto> events;
Нужно добавить приватные модификаторы к полям

2022-11-30 20:19 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/compilation/dto/NewCompilationDto.java
> +    List<Long> events;
Нужно добавить приватные модификаторы к полям

2022-11-30 20:19 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/compilation/model/Compilation.java
> +    Long id;
Нужно добавить модификаторы к полям. Проверьте другие классы модели и дто.

Кроме того, на мой взгляд, коллекции и связи, лучше писать после перечисления остальных полей, в данном случае events лучше писать после title. Не уверен, что это прописано в конвенции, но лично на моей практике обычно делали так

2022-11-30 20:19 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/controller/AdminEventController.java
> +@Slf4j
Не вижу использование логгера в данном классе. На мой взгляд, данная аннотация лишняя.

2022-11-30 20:19 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/controller/EventController.java
> +        EwmPageRequest pageRequest;
Данную конструкцию можно заменить на тернарное выражение, будет выглядеть компактнее.

2022-11-30 20:19 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/controller/EventController.java
> +            pageRequest = new EwmPageRequest(from, size, Sort.by("eventDate").descending());
Типы сортировок предлагаю вынести в enum, их же всего 2

2022-11-30 20:19 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/dto/TwoHourDelayValidator.java
> +        if (LocalDateTime.parse(eventDateTime, DateTimeFormatter.ofPattern("yyyy.MM.dd HH:mm:ss"))
В данном случае не нужно проверять, что eventDateTime != null?

2022-11-30 20:19 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/service/EventServiceImpl.java
> +public class EventServiceImpl implements EventService {
Вообще у меня к Вам 1 вопрос по поводу логирования. Оно же фактически отсутствует. Предлагаю легировать входящие запросы на уровне сервиса. Мне кажется без логирования довольно трудно будет/было отлаживать программу.

2022-11-30 20:19 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/service/EventServiceImpl.java
> +            if (!event.getState().equals(State.PUBLISHED)) {
enum поля правильнее сравнивать через стандартные операторы != и ==, работать будет в любом случае, но стандартные операторы как минимум быстрее

2022-11-30 20:19 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/event/service/EventServiceImpl.java
> +                if (updateEventDto.getPaid() != null) {
Выражения данного типа можно заменить на Optiona.ofNullable(...).ifPresent(...); - будет компактнее и такой код кажется солиднее

2022-11-30 20:19 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/exception/ExceptionHandlerAdvice.java
> +    public String handleServerException(ServerException e) {
А почему сигнатура данного метода от других отличается?

2022-11-30 20:19 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/request/RequestController.java
> +    @GetMapping("/{userId}/requests")
/{userId} - можно в RequestMapping вынести

2022-11-30 20:19 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/request/service/RequestServiceImpl.java
> +            if (status == Status.CONFIRMED && !request.getStatus().equals(Status.CONFIRMED)) {
request.getStatus().equals(Status.CONFIRMED) тоже через стандартный оператор лучше сделать

2022-11-30 20:19 UTC, Frilock commented on ewm-service/src/test/java/ru/practicum/ewmservice/EwmServiceApplicationTests.java
> +class EwmServiceApplicationTests {
Знаю, что в ТЗ у Вас это было задание со звездочкой, но вообще в такой большой работе, хочется увидеть unit тесты, которые тестируют хотя бы сервисы, поскольку это поможет Вам отловить возможные ошибки, а сама работа будет выглядеть солиднее

2022-11-30 20:19 UTC, Frilock commented on stats-server/src/main/java/ru/practicum/statsserver/StatServiceImpl.java
> +            if (unique) {
Данную конструкцию можно заменить на тернарное выражение, будет выглядеть компактнее.

2022-11-30 20:19 UTC, Frilock commented on stats-server/src/test/java/ru/practicum/statsserver/StatsServerApplicationTests.java
> +class StatsServerApplicationTests {
По моему 1 теста достаточно такого типа, ведь этот тест проверяет поднимется ли контекст всего приложения. Поправьте если не прав

2022-11-30 20:19 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/Create.java
> +package ru.practicum.ewmservice;
Под эти классы предлагаю какой нибуть пакет создать, например, utils, туда также перенести PageRequest класс можно

2022-11-30 20:19 UTC, Frilock commented on stats-server/src/main/java/ru/practicum/statsserver/StatMapper.java
> +package ru.practicum.statsserver;
Мне кажется раз вы решили придерживаться правильной раскладки классов по пакетам, то стоит в этом модуле тоже разложить классы правильно

2022-12-01 14:35 UTC, IvanKlimkin commented
Поправил пожелания, иcпользование клиента spring-cloud-starter-openfeign одобрено наставником, по поводу тестов то хотелось бы сконцентрироваться на фичи и соответственно потом дополнить тестовым окружением, к фиче все равно без тестов не обойтись.
Запрос к сервису статистики происходит в модуле EventController , внедряю бин клиента через конструктор, по методам клиента сохраняю и соответственно выгружаю данные с БД статистики.

2022-12-02 08:55 UTC, Frilock approved these changes
Принято

2022-12-02 08:55 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/category/controller/CategoryController.java
> +    public List<CategoryDto> getAll(@PositiveOrZero @RequestParam(
Лучше @RequestParam(name = "from", defaultValue = "0") Integer from на новой строке и 
@RequestParam(name = "size", defaultValue = "10") Integer size тоже

2022-12-02 08:55 UTC, Frilock commented on ewm-service/src/main/java/ru/practicum/ewmservice/client/StatClient.java
> +    @RequestMapping(method = RequestMethod.POST, value = "/hit", consumes = APPLICATION_JSON_VALUE)
Можно PostMapping и GetMapping вместо RequestMapping

2022-12-02 11:39 UTC, merged